services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./resume.db:/app/resume.db
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./fastapitz/front:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge